import "~/styles/globals.css";
// import { getServerSession } from 'next-auth'
// import { authOptions } from '~/server/auth'
import { Inter } from "next/font/google";
import Navbar from '~/components/Navbar'
import Provider from './context/Provider';
import ThemeProvider from './context/next-theme-provider';
import { db } from '~/server/db';

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  console.log(db)
  // const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      {/* <Provider session={session} > */}
        <ThemeProvider attribute='class' enableSystem defaultTheme="dark">
        {/* <Navbar /> */}
      <body className={`font-sans ${inter.variable}`}>{children}</body>
      </ThemeProvider>
      {/* </Provider> */}
    </html>
  );
}
